/* Courses 12–14 use the Tokyo card-and-map presentation. Times are planning
 * targets, not invented timetables; recheck the booked flight and rail schedule. */
const CITY_TRIPS = (() => {
  const place = (name, lng, lat, extra={}) => ({name, coords:[lng,lat], ...extra});
  const make = (config) => {
    const lines=config.lines, legs={};
    const walk=(id,from,to,duration,note,extra={})=>(legs[id]={id,from,to,mode:'walk',duration,note,...extra},id);
    const rail=(id,from,to,line,duration,direction,stops,via=[],extra={})=>(legs[id]={id,from,to,mode:'rail',line,duration,direction,stops,via,...extra},id);
    const reverse=(id,original,direction,note)=>{const a=legs[original];legs[id]={...a,id,from:a.to,to:a.from,reverseOf:original,direction:direction||a.direction,stops:a.stops?.slice().reverse(),note:note||a.note};return id;};
    const step=(id,kind,title,place,time,detail,extra={})=>({id,kind,title,place,time,detail,...extra});
    const journey=(id,title,place,time,route,detail,extra={})=>step(id,'move',title,place,time,detail,{legs:route,...extra});
    config.build({walk,rail,reverse,step,journey});
    return {version:3, checkedAt:'2026-09-29', routeAsset:config.routeAsset, startOverview:true, overviewPlaces:config.overviewPlaces, meta:config.meta, center:config.center, zoom:config.zoom, places:config.places, lines, legs, days:config.days, photos:config.photos};
  };

  const east = (() => {
    const places={
      muc:place('뮌헨 공항 도착장',11.7861,48.3538), mucRail:place('뮌헨 공항역',11.7857,48.3535),
      munichHbf:place('뮌헨 중앙역',11.5583,48.1402), munichHotel:place('뮌헨 중앙역 남쪽 숙소 권역',11.5598,48.1388),
      marien:place('마리엔광장',11.5755,48.1374), viktualien:place('빅투알리엔마르크트',11.5762,48.1354),
      residenz:place('뮌헨 레지덴츠',11.5794,48.1419), englischer:place('영국정원 모노프테로스',11.5898,48.1523),
      fussen:place('퓌센역',10.7005,47.5715), hohenschwangau:place('호엔슈방가우 버스정류장',10.7368,47.5571), neusch:place('노이슈반슈타인성',10.7498,47.5576),
      dresdenHbf:place('드레스덴 중앙역',13.7320,51.0400), dresdenHotel:place('드레스덴 알트마르크트 숙소 권역',13.7381,51.0475),
      altmarkt:place('알트마르크트 · 슈트리첼마르크트',13.7382,51.0492), frauen:place('프라우엔키르헤',13.7416,51.0519), bruhl:place('브륄의 테라스',13.7430,51.0534), zwinger:place('츠빙거 궁전',13.7348,51.0530), neustadt:place('쿤스트호프파사주',13.7536,51.0679),
      berlinHbf:place('베를린 중앙역',13.3695,52.5251), berlinHotel:place('베를린 중앙역 숙소 권역',13.3711,52.5246),
      reichstag:place('독일 국회의사당',13.3762,52.5186), brandenburg:place('브란덴부르크문',13.3777,52.5163), memorial:place('홀로코스트 추모비',13.3787,52.5139), museum:place('박물관섬',13.4002,52.5169), eastside:place('이스트사이드 갤러리',13.4394,52.5050), alex:place('알렉산더광장',13.4132,52.5219),
      warsawCentral:place('바르샤바 중앙역',21.0032,52.2298), warsawHotel:place('바르샤바 중앙역 숙소 권역',21.0050,52.2304), palace:place('문화과학궁전',21.0062,52.2318), castleSquare:place('바르샤바 왕궁광장',21.0141,52.2473), oldTown:place('바르샤바 구시가지 광장',21.0122,52.2498), lazienki:place('와지엔키 궁전',21.0354,52.2150),
      wawRail:place('바르샤바 쇼팽공항역',20.9677,52.1694), waw:place('바르샤바 쇼팽공항 출발장',20.9671,52.1657),
    };
    const lines={S8:{name:'S8 공항철도',badge:'S8',color:'#3577a8'},DB:{name:'DB 장거리열차',badge:'ICE',color:'#c7333e'},RB:{name:'바이에른 지역열차',badge:'RE',color:'#a33c45'},BUS:{name:'호엔슈방가우 버스',badge:'BUS',color:'#4d7f4a'},EC:{name:'유로시티 열차',badge:'EC',color:'#315f91'},S2:{name:'바르샤바 공항철도',badge:'S2',color:'#d55b28'},SB:{name:'베를린 S-Bahn',badge:'S',color:'#4e8b43'}};
    const days=[];
    return make({routeAsset:'assets/citytrips/routes-12.json?v=2',overviewPlaces:['muc','munichHbf','neusch','dresdenHbf','berlinHbf','warsawCentral','waw'],meta:{name:'뮌헨 → 드레스덴 → 베를린 → 바르샤바',period:'9박 10일 본보기 · 저녁 입국 / 낮 출국'},center:[15.5,50.3],zoom:4.7,places,lines,days,photos:{munich:'qa_c9_cover_munich_base',neusch:'qa_c9_d8_neuschwanstein_0',dresden:{url:'https://commons.wikimedia.org/wiki/Special:FilePath/Dresden-Frauenkirche-night.jpg?width=1280',source:'https://commons.wikimedia.org/wiki/File:Dresden-Frauenkirche-night.jpg',credit:'Wikimedia Commons',caption:'드레스덴 프라우엔키르헤'},berlin:'qa_c3_d3_1',warsaw:{url:'https://commons.wikimedia.org/wiki/Special:FilePath/Warsaw_Old_Town_Market_Square_2022.jpg?width=1280',source:'https://commons.wikimedia.org/wiki/File:Warsaw_Old_Town_Market_Square_2022.jpg',credit:'Wikimedia Commons',caption:'바르샤바 구시가지'}},build:({walk,rail,reverse,step,journey})=>{
      rail('muc-city','mucRail','munichHbf','S8','약 45분','시내 방면 · 중앙역 하차',['공항','동역','마리엔광장','중앙역'],[[11.70,48.31],[11.65,48.25],[11.604,48.18]]);
      walk('hbf-mhotel','munichHbf','munichHotel','약 5분','중앙역 남쪽 출구에서 예약한 숙소까지.'); reverse('mhotel-hbf','hbf-mhotel');
      rail('hbf-marien','munichHbf','marien','S8','약 5분','동역 방면 · 마리엔광장 하차',['중앙역','칼스플라츠','마리엔광장'],[[11.5668,48.1394]]);
      walk('marien-vikt','marien','viktualien','약 4분','신시청사를 보고 시장 방향으로 내려가요.'); walk('vikt-residenz','viktualien','residenz','약 12분','구시가지 보행자 구역을 따라 레지덴츠로.'); walk('residenz-garden','residenz','englischer','약 18분','호프가르텐을 지나 영국정원 남쪽으로.');
      rail('munich-fussen','munichHbf','fussen','RB','약 2시간','부흘로에 경유 퓌센행',['뮌헨','부흘로에','카우프보이렌','퓌센'],[[11.10,48.00],[10.72,47.88]]);
      rail('fussen-bus','fussen','hohenschwangau','BUS','약 10분','73·78번 버스 · 성 방면',['퓌센역','호엔슈방가우'],[[10.71,47.565],[10.724,47.560]]);
      walk('bus-neusch','hohenschwangau','neusch','약 35~45분 오르막','겨울에는 셔틀버스·마차보다 도보 시간을 넉넉히 잡아요.'); reverse('neusch-bus','bus-neusch',null,'예약 관람 후 같은 길로 버스정류장까지 내려와요.'); reverse('bus-fussen','fussen-bus','퓌센역 방면'); reverse('fussen-munich','munich-fussen','뮌헨 중앙역 방면');
      rail('munich-dresden','munichHbf','dresdenHbf','DB','약 4시간 30분','예약 열차 기준 1회 환승',['뮌헨','뉘른베르크','에르푸르트','라이프치히','드레스덴'],[[11.082,49.446],[11.038,50.980],[12.382,51.345]]);
      walk('dhbf-dhotel','dresdenHbf','dresdenHotel','약 15분','프라거 슈트라세를 따라 알트마르크트 숙소 권역으로.'); walk('dhotel-alt','dresdenHotel','altmarkt','약 3분','숙소에서 알트마르크트 광장으로.'); walk('alt-frauen','altmarkt','frauen','약 7분','구시가지 골목을 지나 노이마르크트로.'); walk('frauen-bruhl','frauen','bruhl','약 5분','교회 북쪽 골목을 지나 엘베강 테라스로.'); walk('bruhl-zwinger','bruhl','zwinger','약 10분','젬퍼오퍼를 지나 츠빙거 안뜰로.');
      walk('zwinger-dhbf','zwinger','dresdenHbf','약 20분','프라거 슈트라세 방향으로 중앙역까지 걸어요.'); rail('dresden-neustadt','dresdenHbf','neustadt','DB','약 15분','S-Bahn 후 도보 또는 트램',['중앙역','노이슈타트'],[[13.739,51.050],[13.741,51.060]]);
      rail('dresden-berlin','dresdenHbf','berlinHbf','DB','약 2시간','베를린행 직통 EC/IC',['드레스덴','엘스터베르다','베를린 남십자','베를린 중앙역'],[[13.520,51.461],[13.365,52.475]]);
      walk('bhbf-bhotel','berlinHbf','berlinHotel','약 5분','워싱턴 광장 쪽 숙소 권역으로.'); walk('bhotel-reich','berlinHotel','reichstag','약 14분','슈프레강을 건너 국회의사당으로.'); walk('reich-brand','reichstag','brandenburg','약 6분','공화국 광장에서 브란덴부르크문으로.'); walk('brand-memorial','brandenburg','memorial','약 4분','에베르트 거리를 따라 남쪽으로.');
      rail('bhbf-museum','berlinHbf','museum','SB','약 10분','S-Bahn 동쪽 방면 · 하케셔마르크트권',['중앙역','프리드리히슈트라세','하케셔마르크트'],[[13.388,52.520]]); rail('museum-east','museum','eastside','SB','약 20분','알렉산더광장 환승 · 동역 하차',['박물관섬','알렉산더광장','동역'],[[13.413,52.522],[13.435,52.510]]); rail('east-alex','eastside','alex','SB','약 10분','S-Bahn 서쪽 방면',['동역','야노비츠브뤼케','알렉산더광장'],[[13.428,52.514]]);
      rail('berlin-warsaw','berlinHbf','warsawCentral','EC','약 5시간 30분','Berlin–Warszawa Express · 좌석 예약 권장',['베를린','프랑크푸르트(오데르)','포즈난','바르샤바'],[[14.55,52.34],[16.925,52.406],[19.45,52.12]]);
      walk('wcentral-whotel','warsawCentral','warsawHotel','약 5분','중앙역에서 문화과학궁전 쪽 숙소 권역으로.'); reverse('whotel-wcentral','wcentral-whotel'); walk('whotel-palace','warsawHotel','palace','약 4분','숙소에서 문화과학궁전 광장으로.');
      rail('palace-old','palace','castleSquare','S2','약 20분','트램 또는 M2 · 구시가지 방면',['센트룸','시비엥톡시스카','구시가지'],[[21.012,52.237],[21.012,52.242]]); walk('castle-old','castleSquare','oldTown','약 5분','왕궁광장에서 구시가지 광장까지.'); rail('old-lazienki','oldTown','lazienki','S2','약 30분','116·180번 버스 계열 · 와지엔키 방면',['구시가지','노비시비아트','와지엔키 공원'],[[21.021,52.239],[21.030,52.225]]);
      rail('central-waw','warsawCentral','wawRail','S2','약 25분','공항행 S2/S30 · 터미널 확인',['중앙역','서역','쇼팽공항'],[[20.990,52.220],[20.975,52.190]]); walk('wawrail-terminal','wawRail','waw','약 5~10분','표지를 따라 예약 항공사 출발장으로.');

      days.push(
        {date:'입국일',title:'저녁 뮌헨 입국',subtitle:'18시 전후 도착 가정 · 첫날은 숙소까지만',steps:[step('muc-arrival','arrival','뮌헨에 도착','muc','18:00 도착 가정','입국심사와 수하물 수령 뒤 S-Bahn 표지를 따라 공항역으로 가요.',{facts:['항공편·터미널은 예약 후 확정','첫날 관광은 넣지 않고 숙소 체크인에 집중']}),journey('muc-transfer','공항 → 뮌헨 중앙역','munichHbf','20:00 전후',['muc-city'],'S8 또는 S1 중 먼저 오는 편을 확인하되, 본보기에서는 S8을 사용해요.'),journey('munich-checkin','숙소 체크인','munichHotel','21:00 전후',['hbf-mhotel'],'중앙역 남쪽 숙소 권역에 체크인하고 가까운 곳에서 늦은 저녁을 먹어요.',{photo:'munich',highlights:['물·아침거리 준비','다음 날 교통권 확인']})]},
        {date:'2일차',title:'뮌헨 구시가지와 영국정원',subtitle:'도보 중심으로 도시의 첫인상을 잡는 날',steps:[journey('munich-oldtown','중앙역 → 마리엔광장','marien','09:00',['mhotel-hbf','hbf-marien'],'S-Bahn 두 정거장으로 구시가지 중심에 들어가요.',{photo:'munich'}),journey('munich-market','빅투알리엔마르크트','viktualien','오전',['marien-vikt'],'신시청사와 프라우엔키르헤 주변을 본 뒤 시장으로 내려가요.',{highlights:['마리엔광장','시장 간단한 점심']}),journey('munich-residenz','레지덴츠와 호프가르텐','residenz','오후',['vikt-residenz'],'구시가지 북쪽으로 이동해 궁전 또는 보물관을 한 곳 골라요.'),journey('munich-garden','영국정원 산책','englischer','해 지기 전',['residenz-garden'],'호프가르텐에서 영국정원 남쪽까지 걸어요.',{highlights:['겨울에는 일몰 전에 공원 마무리','귀가는 오데온스플라츠 U-Bahn 이용']})]},
        {date:'3일차',title:'노이슈반슈타인 당일치기',subtitle:'예약 관람시간을 기준으로 역산',steps:[journey('fussen-out','뮌헨 → 퓌센','fussen','07:30 출발 목표',['mhotel-hbf','munich-fussen'],'지역열차는 환승 가능성을 열어 두고, 성 예약시간보다 충분히 일찍 출발해요.'),journey('castle-bus','퓌센 → 호엔슈방가우','hohenschwangau','10:00 전후',['fussen-bus'],'역 앞 버스로 성 아래 마을까지 이동해요.'),journey('castle-climb','노이슈반슈타인성 오르기','neusch','예약 60분 전',['bus-neusch'],'겨울 결빙을 감안해 도보 기준으로 잡았어요.',{photo:'neusch',highlights:['성 내부 시간 지정권 사전 예약','마리엔교는 겨울 폐쇄 가능']}),journey('castle-return','뮌헨으로 귀환','munichHotel','16:00~20:00',['neusch-bus','bus-fussen','fussen-munich','hbf-mhotel'],'어두워지기 전에 하산해 퓌센역에서 뮌헨행 열차를 타요.') ]},
        {date:'4일차',title:'뮌헨에서 드레스덴으로',subtitle:'오전 열차 · 오후 구시가지',steps:[journey('to-dresden','뮌헨 → 드레스덴','dresdenHbf','08:00~13:00',['mhotel-hbf','munich-dresden'],'예약 가능한 장거리열차로 이동해요. 실제 시간표에 따라 환승역은 바뀔 수 있어요.'),journey('dresden-checkin','드레스덴 숙소 체크인','dresdenHotel','도착 후',['dhbf-dhotel'],'프라거 슈트라세를 걸어 알트마르크트권 숙소로.',{photo:'dresden'}),journey('dresden-market','알트마르크트 첫 산책','altmarkt','오후~밤',['dhotel-alt'],'크리스마스 시즌이면 슈트리첼마르크트를 첫날 저녁에 봐요.',{highlights:['마켓 종료일은 연도별 확인','슈톨렌·글뤼바인']})]},
        {date:'5일차',title:'드레스덴을 온전히',subtitle:'바로크 구시가지와 엘베강',steps:[journey('dresden-frauen','프라우엔키르헤','frauen','09:30',['dhotel-alt','alt-frauen'],'알트마르크트에서 노이마르크트로 천천히 걸어요.',{photo:'dresden'}),journey('dresden-bruhl','브륄의 테라스','bruhl','점심 전',['frauen-bruhl'],'엘베강과 구시가지 스카이라인을 봐요.'),journey('dresden-zwinger','젬퍼오퍼와 츠빙거','zwinger','오후',['bruhl-zwinger'],'박물관 하나만 골라 실내 관람량을 조절해요.'),journey('dresden-newtown','노이슈타트 저녁','neustadt','저녁',['zwinger-dhbf','dresden-neustadt'],'중앙역을 거쳐 신시가지로 이동해 골목과 식당을 둘러봐요.') ]},
        {date:'6일차',title:'드레스덴에서 베를린으로',subtitle:'짧은 도시간 이동 뒤 역사 산책',steps:[journey('to-berlin','드레스덴 → 베를린','berlinHbf','09:00~11:00',['dresden-berlin'],'직통 EC/IC를 우선하고 좌석을 예약해요.'),journey('berlin-checkin','베를린 숙소에 짐 맡기기','berlinHotel','도착 후',['bhbf-bhotel'],'중앙역 가까운 숙소 권역으로 이동해 짐을 맡겨요.'),journey('berlin-reichstag','국회의사당','reichstag','오후',['bhotel-reich'],'강변을 따라 국회의사당으로 걸어요.',{photo:'berlin'}),journey('berlin-core','브란덴부르크문과 추모비','memorial','해 질 무렵',['reich-brand','brand-memorial'],'브란덴부르크문에서 홀로코스트 추모비까지 이어 걸어요.',{highlights:['국회의사당 돔은 사전 등록','야간에는 큰길 이용']})]},
        {date:'7일차',title:'베를린 동서 횡단',subtitle:'박물관섬과 장벽의 흔적',steps:[journey('berlin-museum','박물관섬','museum','09:30',['bhbf-museum'],'원하는 박물관 하나를 예약해 오전에 봐요.',{photo:'berlin',highlights:['페르가몬 본관 장기 공사 여부 확인','입장 예약 확인']}),journey('berlin-eastside','이스트사이드 갤러리','eastside','오후',['museum-east'],'S-Bahn으로 동역권으로 이동해 장벽 벽화를 걸어요.'),journey('berlin-alex','알렉산더광장','alex','저녁',['east-alex'],'알렉산더광장 쪽으로 돌아와 저녁을 먹고 중앙역으로 귀가해요.') ]},
        {date:'8일차',title:'베를린에서 바르샤바로',subtitle:'낮 대부분을 쓰는 국제열차 이동',steps:[journey('to-warsaw','베를린 → 바르샤바','warsawCentral','08:30~14:00',['berlin-warsaw'],'직통 EuroCity 좌석을 예약하고 여권을 휴대해요. 솅겐 내부지만 신분 확인 가능성은 있어요.'),journey('warsaw-checkin','바르샤바 숙소 체크인','warsawHotel','도착 후',['wcentral-whotel'],'중앙역 인근 숙소에 짐을 둬요.'),journey('warsaw-palace','문화과학궁전과 센트룸','palace','오후~저녁',['whotel-palace'],'전망대 또는 주변 광장만 가볍게 보고 쉬어요.',{photo:'warsaw'})]},
        {date:'9일차',title:'바르샤바 구시가지와 공원',subtitle:'마지막 완전한 하루',steps:[journey('warsaw-old-out','왕궁광장으로','castleSquare','09:30',['palace-old'],'대중교통으로 구시가지 남쪽 입구까지 이동해요.'),journey('warsaw-old','구시가지 광장','oldTown','오전~점심',['castle-old'],'왕궁광장, 성 요한 대성당, 구시가지 광장을 연결해 걸어요.',{photo:'warsaw'}),journey('warsaw-lazienki','와지엔키 공원','lazienki','오후',['old-lazienki'],'구시가지에서 버스로 공원에 가요.',{highlights:['겨울에는 해 지기 전 산책 종료','마지막 저녁 후 짐 정리']})]},
        {date:'출국일',title:'낮 비행기로 출국',subtitle:'13시 출발 가정 · 공항 3시간 전 도착',steps:[step('warsaw-checkout','departure','체크아웃','warsawHotel','08:30','아침 식사 뒤 체크아웃하고 중앙역 공항철도 승강장으로 가요.',{facts:['온라인 체크인','수하물·터미널 재확인']}),journey('waw-transfer','바르샤바 중앙역 → 쇼팽공항','wawRail','09:00',['whotel-wcentral','central-waw'],'S2/S30 중 운행편을 확인해 공항역으로 이동해요.'),journey('waw-depart','바르샤바 출국','waw','10:00 공항 도착 · 13:00 출발 가정',['wawrail-terminal'],'체크인과 출국심사를 마치고 귀국편에 탑승해요.') ]}
      );
    }});
  })();

  const north = (() => {
    const places={fra:place('프랑크푸르트공항 도착장',8.5706,50.0379),fraRail:place('프랑크푸르트공항 지역열차역',8.5712,50.0512),frankHbf:place('프랑크푸르트 중앙역',8.6638,50.1071),frankHotel:place('프랑크푸르트 중앙역 숙소 권역',8.6660,50.1081),romer:place('뢰머베르크',8.6821,50.1109),iron:place('아이제르너 슈테크',8.6827,50.1077),mainTower:place('마인 타워',8.6722,50.1122),heidHbf:place('하이델베르크 중앙역',8.6752,49.4036),heidOld:place('하이델베르크 비스마르크광장',8.6937,49.4092),oldBridge:place('하이델베르크 옛다리',8.7095,49.4141),castle:place('하이델베르크성',8.7158,49.4104),strasHbf:place('스트라스부르역',7.7346,48.5850),strasCat:place('스트라스부르 대성당',7.7508,48.5818),petite:place('쁘띠 프랑스',7.7425,48.5810),cologneHbf:place('쾰른 중앙역',6.9584,50.9430),cathedral:place('쾰른 대성당',6.9583,50.9413),bridge:place('호엔촐레른 다리 전망',6.9694,50.9416),oldCologne:place('쾰른 알터 마르크트',6.9603,50.9387),hamburgHbf:place('함부르크 중앙역',10.0067,53.5527),hamburgHotel:place('함부르크 중앙역 숙소 권역',10.0081,53.5540),rathaus:place('함부르크 시청',9.9920,53.5504),speicher:place('슈파이허슈타트 바서슐로스',10.0021,53.5438),elphi:place('엘프필하모니',9.9842,53.5413),landungs:place('란둥스브뤼켄',9.9660,53.5461),alster:place('융페른슈티크 · 알스터호',9.9930,53.5539),hamRail:place('함부르크공항역',10.0069,53.6322),ham:place('함부르크공항 출발장',10.0064,53.6304)};
    const lines={S8:{name:'S8/S9 공항철도',badge:'S',color:'#287b50'},RE:{name:'DB 지역열차',badge:'RE',color:'#b34747'},ICE:{name:'ICE 장거리열차',badge:'ICE',color:'#d13b45'},TGV:{name:'ICE/TGV 국제열차',badge:'TGV',color:'#7650a1'},U:{name:'도시 대중교통',badge:'U·S',color:'#3978a8'},S1:{name:'함부르크 S1',badge:'S1',color:'#2f8b63'}};
    const days=[];
    return make({routeAsset:'assets/citytrips/routes-13.json?v=2',overviewPlaces:['fra','frankHbf','heidOld','strasCat','cathedral','hamburgHbf','ham'],meta:{name:'프랑크푸르트 → 함부르크',period:'8박 9일 본보기 · 저녁 입국 / 낮 출국'},center:[8.8,51.7],zoom:5.4,places,lines,days,photos:{frank:'qa_c9_d2_rich_009',heid:'qa_c9_d4_rich_024',stras:'c8_strasbourg_cathedral',cologne:'qa_c3_d5_0',hamburg:'qa_c3_d4_0'},build:({walk,rail,reverse,step,journey})=>{
      rail('fra-city','fraRail','frankHbf','S8','약 15분','시내 방면 · 중앙역 하차',['공항','슈타디온','중앙역'],[[8.61,50.07],[8.64,50.09]]); walk('fhbf-fhotel','frankHbf','frankHotel','약 5분','중앙역 북쪽 숙소 권역으로.'); reverse('fhotel-fhbf','fhbf-fhotel');
      rail('fhbf-romer','frankHbf','romer','U','약 12분','U4/U5 또는 트램 · 뢰머권',['중앙역','빌리브란트광장','뢰머'],[[8.674,50.108]]); walk('romer-iron','romer','iron','약 5분','구시가지에서 마인강 쪽으로.'); walk('iron-maintower','iron','mainTower','약 18분','강변과 금융가를 지나 전망대로.');
      rail('frank-heid','frankHbf','heidHbf','RE','약 55~75분','직통 또는 만하임 환승',['프랑크푸르트','다름슈타트','바인하임','하이델베르크'],[[8.652,49.872],[8.61,49.55]]); reverse('heid-frank','frank-heid','프랑크푸르트 방면'); rail('heid-old','heidHbf','heidOld','U','약 10분','트램 5·21·24 계열 · 비스마르크광장',['중앙역','비스마르크광장'],[[8.685,49.406]]); reverse('old-heid','heid-old','중앙역 방면'); walk('heid-bridge','heidOld','oldBridge','약 22분','하우프트슈트라세 보행자길을 끝까지.'); reverse('bridge-heid','heid-bridge'); walk('bridge-castle','oldBridge','castle','약 18분 오르막','코른마르크트에서 푸니쿨라 또는 도보로 성까지.'); reverse('castle-bridge','bridge-castle');
      rail('frank-stras','frankHbf','strasHbf','TGV','약 1시간 50분','예약 가능한 직통편 우선',['프랑크푸르트','만하임','카를스루에','스트라스부르'],[[8.469,49.479],[8.404,48.994],[7.850,48.67]]); reverse('stras-frank','frank-stras','프랑크푸르트 방면'); walk('stras-cat','strasHbf','strasCat','약 18분','그랑딜 골목을 지나 대성당으로.'); walk('cat-petite','strasCat','petite','약 12분','구시가지를 가로질러 운하 지구로.'); walk('petite-stras','petite','strasHbf','약 12분','운하를 따라 역 광장으로 돌아가요.');
      rail('frank-cologne','frankHbf','cologneHbf','ICE','약 1시간 5분','고속선 직통 ICE',['프랑크푸르트','림부르크 남역','몬타바우어','지크부르크/본','쾰른'],[[8.096,50.382],[7.825,50.445],[7.203,50.794]]); reverse('cologne-frank','frank-cologne','프랑크푸르트 방면'); walk('cologne-cat','cologneHbf','cathedral','약 2분','역 남쪽 출구 바로 앞 대성당으로.'); walk('cat-bridge','cathedral','bridge','약 12분','역 뒤편에서 호엔촐레른 다리를 건너요.'); walk('bridge-old','bridge','oldCologne','약 18분','라인강변을 따라 알터 마르크트로 돌아와요.'); walk('old-colognehbf','oldCologne','cologneHbf','약 10분','대성당을 기준으로 중앙역까지 돌아가요.');
      rail('frank-hamburg','frankHbf','hamburgHbf','ICE','약 3시간 40분~4시간','직통 ICE · 좌석 예약 권장',['프랑크푸르트','카셀빌헬름스회에','괴팅겐','하노버','함부르크'],[[9.447,51.312],[9.93,51.537],[9.742,52.377]]); walk('hhbf-hhotel','hamburgHbf','hamburgHotel','약 5분','중앙역 동쪽 또는 북쪽 숙소 권역으로.'); reverse('hhotel-hhbf','hhbf-hhotel');
      rail('hhbf-rathaus','hamburgHbf','rathaus','U','약 8분','U3 또는 S-Bahn · 시청권',['중앙역','융페른슈티크','시청'],[[9.999,53.553]]); walk('rathaus-speicher','rathaus','speicher','약 15분','니콜라이 기념관을 지나 슈파이허슈타트로.'); walk('speicher-elphi','speicher','elphi','약 12분','창고지구 수로를 따라 엘프필하모니로.'); rail('hhbf-landungs','hamburgHbf','landungs','U','약 15분','U3 순환선 · 란둥스브뤼켄',['중앙역','시청','바움발','란둥스브뤼켄'],[[9.992,53.55],[9.98,53.545]]); rail('landungs-alster','landungs','alster','U','약 10분','U3/S-Bahn · 융페른슈티크',['란둥스브뤼켄','융페른슈티크'],[[9.980,53.551]]);
      rail('hhbf-ham','hamburgHbf','hamRail','S1','약 25분','공항행 S1 · 오홀스도르프 분리 확인',['중앙역','오홀스도르프','공항'],[[10.018,53.59],[10.031,53.625]]); walk('hamrail-terminal','hamRail','ham','약 5분','엘리베이터로 예약 항공사 출발층으로.');
      days.push(
        {date:'입국일',title:'저녁 프랑크푸르트 입국',subtitle:'18시 전후 도착 가정',steps:[step('fra-arrival','arrival','프랑크푸르트에 도착','fra','18:00 도착 가정','입국심사와 수하물 수령 후 지역열차역 표지를 따라가요.'),journey('fra-transfer','공항 → 중앙역','frankHbf','20:00 전후',['fra-city'],'S8/S9로 시내까지 이동해요.'),journey('frank-checkin','숙소 체크인','frankHotel','20:30 전후',['fhbf-fhotel'],'중앙역 인근에 체크인하고 무리 없이 첫날을 마쳐요.',{photo:'frank'})]},
        {date:'2일차',title:'프랑크푸르트 집중일',subtitle:'구시가지·마인강·스카이라인',steps:[journey('frank-romer','뢰머베르크','romer','09:30',['fhotel-fhbf','fhbf-romer'],'대중교통으로 구시가지 중심까지 이동해요.',{photo:'frank'}),journey('frank-river','마인강과 아이제르너 슈테크','iron','점심 전',['romer-iron'],'대성당과 신구시가지를 본 뒤 다리로 내려가요.'),journey('frank-skyline','마인 타워와 금융가','mainTower','해 질 무렵',['iron-maintower'],'강변에서 금융가까지 걸어 전망대 입장시간을 맞춰요.',{highlights:['마인 타워는 운영·날씨 확인','저녁은 작센하우젠 후보']})]},
        {date:'3일차',title:'하이델베르크 당일치기',subtitle:'구시가지와 성, 저녁 프랑크푸르트 복귀',steps:[journey('heid-out','프랑크푸르트 → 하이델베르크','heidOld','08:00~10:00',['fhotel-fhbf','frank-heid','heid-old'],'열차와 트램을 이어 비스마르크광장부터 시작해요.'),journey('heid-walk','구시가지 → 옛다리','oldBridge','오전~점심',['heid-bridge'],'하우프트슈트라세와 성령교회를 지나 옛다리까지 걸어요.',{photo:'heid'}),journey('heid-castle','하이델베르크성','castle','오후',['bridge-castle'],'오르막은 푸니쿨라를 이용해도 좋아요.',{highlights:['성 내부·대형 와인통 운영 확인','겨울에는 철학자의 길 대신 성 전망 우선']}),journey('heid-return','프랑크푸르트 복귀','frankHotel','17:00~19:00',['castle-bridge','bridge-heid','old-heid','heid-frank','fhbf-fhotel'],'구시가지와 중앙역을 거쳐 지역열차 또는 ICE로 복귀해요.') ]},
        {date:'4일차',title:'스트라스부르 당일치기',subtitle:'국제열차로 알자스 왕복',steps:[journey('stras-out','프랑크푸르트 → 스트라스부르','strasHbf','07:30~10:00',['fhotel-fhbf','frank-stras'],'직통 ICE/TGV를 우선하고 여권을 휴대해요.'),journey('stras-core','대성당과 그랑딜','strasCat','오전',['stras-cat'],'역에서 구시가지까지 걸어 대성당을 먼저 봐요.',{photo:'stras'}),journey('stras-petite','쁘띠 프랑스','petite','오후',['cat-petite'],'운하 지구를 걷고 이른 저녁을 먹어요.'),journey('stras-return','프랑크푸르트 복귀','frankHotel','18:00~21:00',['petite-stras','stras-frank','fhbf-fhotel'],'역으로 돌아가 예약한 국제열차로 프랑크푸르트에 복귀해요.') ]},
        {date:'5일차',title:'쾰른 당일치기',subtitle:'대성당과 라인강',steps:[journey('cologne-out','프랑크푸르트 → 쾰른','cologneHbf','08:30~10:00',['fhotel-fhbf','frank-cologne'],'고속선 ICE로 이동해 역 바로 앞 대성당부터 시작해요.'),journey('cologne-cathedral','쾰른 대성당','cathedral','오전',['cologne-cat'],'내부 관람과 탑 입장 중 체력에 맞춰 선택해요.',{photo:'cologne'}),journey('cologne-rhine','호엔촐레른 다리','bridge','점심 후',['cat-bridge'],'다리를 건너 대성당 정면 전망을 봐요.'),journey('cologne-old','라인강변과 구시가지','oldCologne','오후',['bridge-old'],'강변을 따라 구시가지로 돌아와요.'),journey('cologne-return','프랑크푸르트 복귀','frankHotel','18:00~20:00',['old-colognehbf','cologne-frank','fhbf-fhotel'],'중앙역으로 돌아가 저녁 ICE로 같은 숙소에 복귀해요.') ]},
        {date:'6일차',title:'프랑크푸르트에서 함부르크로',subtitle:'오전 ICE · 오후 항구도시',steps:[journey('to-hamburg','프랑크푸르트 → 함부르크','hamburgHbf','08:30~12:30',['fhotel-fhbf','frank-hamburg'],'직통 ICE 좌석을 예약해 북상해요.'),journey('hamburg-checkin','함부르크 숙소 체크인','hamburgHotel','도착 후',['hhbf-hhotel'],'중앙역 인근에 짐을 두고 점심을 먹어요.',{photo:'hamburg'}),journey('hamburg-rathaus','함부르크 시청','rathaus','오후',['hhbf-rathaus'],'융페른슈티크와 시청 광장을 먼저 봐요.') ]},
        {date:'7일차',title:'슈파이허슈타트와 하펜시티',subtitle:'물길과 붉은 벽돌의 하루',steps:[journey('hamburg-old','시청에서 슈파이허슈타트로','speicher','09:30',['hhbf-rathaus','rathaus-speicher'],'시청에서 창고지구까지 걸어요.',{photo:'hamburg'}),journey('hamburg-elphi','엘프필하모니','elphi','오후',['speicher-elphi'],'플라자 입장권을 확보했다면 항구 전망까지 봐요.',{highlights:['미니어처 원더랜드는 별도 사전예약','엘프필하모니 플라자 시간 확인']})]},
        {date:'8일차',title:'항구와 알스터호',subtitle:'함부르크의 서로 다른 물가',steps:[journey('hamburg-port','란둥스브뤼켄','landungs','오전',['hhotel-hhbf','hhbf-landungs'],'중앙역에서 U3로 항구까지 이동해 페리 또는 엘베터널을 골라요.'),journey('hamburg-alster','알스터호와 융페른슈티크','alster','오후',['landungs-alster'],'항구에서 도심 호수권으로 돌아와 마지막 쇼핑을 해요.',{photo:'hamburg',highlights:['항만 페리는 HVV권 적용 노선 확인','다음 날 S1 운행 확인']})]},
        {date:'출국일',title:'낮 비행기로 출국',subtitle:'13시 출발 가정 · 공항 3시간 전 도착',steps:[step('hamburg-checkout','departure','체크아웃','hamburgHotel','08:30','아침 식사 뒤 체크아웃하고 중앙역 S-Bahn으로 가요.'),journey('ham-transfer','중앙역 → 함부르크공항','hamRail','09:00',['hhotel-hhbf','hhbf-ham'],'S1 공항행 차량을 확인해 탑승해요.'),journey('ham-depart','함부르크 출국','ham','10:00 공항 도착 · 13:00 출발 가정',['hamrail-terminal'],'출발층에서 체크인과 보안검색을 마쳐요.') ]}
      );
    }});
  })();

  const france = (() => {
    const places={strasHbf:place('스트라스부르역',7.7346,48.5850),strasHotel:place('스트라스부르역 숙소 권역',7.7381,48.5842),petite:place('쁘띠 프랑스',7.7425,48.5810),cathedral:place('스트라스부르 대성당',7.7508,48.5818),kleber:place('클레베르 광장',7.7452,48.5835),orangerie:place('오랑주리 공원',7.7752,48.5903),european:place('유럽의회',7.7681,48.5975),parisEst:place('파리 동역',2.3590,48.8763),parisHotel:place('파리 동역 숙소 권역',2.3573,48.8750),louvre:place('루브르 피라미드',2.3376,48.8606),tuileries:place('튈르리 정원',2.3271,48.8635),concorde:place('콩코르드 광장',2.3212,48.8656),notre:place('노트르담 대성당',2.3499,48.8530),saintGermain:place('생제르맹데프레',2.3332,48.8539),montmartre:place('사크레쾨르 대성당',2.3431,48.8867),arc:place('개선문',2.2950,48.8738),eiffel:place('에펠탑',2.2945,48.8584),gareNord:place('파리 북역 RER B',2.3553,48.8809),cdgRail:place('CDG 2 TGV · RER역',2.5708,49.0040),cdg:place('CDG 터미널 2',2.5717,49.0030)};
    const lines={TGV:{name:'TGV INOUI',badge:'TGV',color:'#7650a1'},TRAM:{name:'스트라스부르 트램',badge:'TRAM',color:'#4f8a62'},METRO:{name:'파리 Métro',badge:'M',color:'#396aa7'},RER:{name:'RER B 공항철도',badge:'RER',color:'#467eaa'}};
    const days=[];
    return make({routeAsset:'assets/citytrips/routes-14.json?v=3',overviewPlaces:['cdg','strasHbf','parisEst'],meta:{name:'스트라스부르 → 파리',period:'9박 10일 본보기 · 파리 CDG 왕복'},center:[4.9,49.0],zoom:5.7,places,lines,days,photos:{stras:'c8_strasbourg_cathedral',petite:'c8_strasbourg_petite_france',paris:'eiffel_tower',louvre:'qa_c3_d12_1',montmartre:'qa_c3_d15_0'},build:({walk,rail,reverse,step,journey})=>{
      walk('terminal-cdgrail','cdg','cdgRail','약 10~20분','도착장에서 Aéroport Charles de Gaulle 2 TGV 표지를 따라가요.');
      rail('cdg-stras','cdgRail','strasHbf','TGV','약 1시간 50분~2시간 15분','스트라스부르행 직통 TGV · 지정석',['CDG 2 TGV','샹파뉴아르덴 TGV','로렌 TGV','스트라스부르'],[[3.05,48.94],[4.05,49.00],[6.15,48.98],[7.10,48.75]]);
      walk('stras-hotel','strasHbf','strasHotel','약 6분','역 광장에서 숙소 권역으로.'); reverse('hotel-stras','stras-hotel');
      walk('hotel-petite','strasHotel','petite','약 10분','운하를 따라 쁘띠 프랑스로.'); walk('petite-cat','petite','cathedral','약 12분','그랑딜 골목을 지나 대성당으로.'); walk('cat-kleber','cathedral','kleber','약 7분','구시가지 쇼핑 거리를 따라 클레베르 광장으로.');
      rail('stras-orangerie','strasHbf','orangerie','TRAM','약 25분','트램 C/E와 도보 조합',['역','레퓌블리크','오랑주리'],[[7.751,48.588],[7.764,48.590]]); walk('orangerie-eu','orangerie','european','약 15분','공원 북쪽에서 유럽지구로.'); rail('eu-cat','european','cathedral','TRAM','약 25분','트램 E 후 도보 · 도심 방면',['유럽의회','레퓌블리크','구시가지'],[[7.759,48.592],[7.750,48.586]]);
      rail('stras-paris','strasHbf','parisEst','TGV','약 1시간 45분','파리 동역행 직통 TGV · 지정석',['스트라스부르','로렌 TGV권','샹파뉴아르덴권','파리 동역'],[[7.10,48.75],[6.15,48.98],[4.05,49.0],[2.80,48.90]]); reverse('paris-stras','stras-paris','스트라스부르행 직통 TGV · 지정석'); walk('est-photel','parisEst','parisHotel','약 5분','동역 남쪽 숙소 권역으로.'); reverse('photel-est','est-photel');
      rail('est-louvre','parisEst','louvre','METRO','약 20분','Métro 7 · Palais Royal–Musée du Louvre',['동역','오페라권','팔레루아얄'],[[2.350,48.870],[2.342,48.864]]); walk('louvre-tuileries','louvre','tuileries','약 10분','카루젤 개선문을 지나 정원으로.'); walk('tuileries-concorde','tuileries','concorde','약 10분','정원 서쪽 끝까지 직진해요.');
      rail('est-notre','parisEst','notre','METRO','약 25분','Métro 4 · 시테역 하차',['동역','샤틀레','시테'],[[2.347,48.866],[2.347,48.858]]); walk('notre-sg','notre','saintGermain','약 18분','센강 남안을 따라 생제르맹으로.'); rail('est-montmartre','parisEst','montmartre','METRO','약 20분','Métro 4/2 또는 버스 · 앙베르권',['동역','바르베스','앙베르'],[[2.351,48.883]]); rail('montmartre-arc','montmartre','arc','METRO','약 30분','Métro 2 · Charles de Gaulle–Étoile',['앙베르','피갈','몽소','개선문'],[[2.326,48.883],[2.310,48.881]]); rail('est-arc','parisEst','arc','METRO','약 25분','Métro 4/1 환승 · 개선문',['동역','샤틀레','개선문'],[[2.347,48.866],[2.320,48.869]]); rail('arc-eiffel','arc','eiffel','METRO','약 25분','Métro 6 · Trocadéro 후 도보',['개선문','트로카데로','에펠탑'],[[2.287,48.863]]);
      walk('photel-nord','parisHotel','gareNord','약 10분','큰길을 따라 북역 RER B 승강장으로.'); rail('nord-cdg','gareNord','cdgRail','RER','약 35분','Aéroport Charles de Gaulle 2행 직통 계통',['파리 북역','CDG 1','CDG 2'],[[2.42,48.92],[2.53,48.98]]); reverse('cdg-nord','nord-cdg','파리 북역행 RER B'); walk('nord-est','gareNord','parisEst','약 8~12분','북역에서 Rue d’Alsace 방면으로 나와 파리 동역까지 걸어요.'); walk('cdgrail-terminal','cdgRail','cdg','약 10~20분','예약 항공사 터미널을 확인하고 셔틀·연결통로 표지를 따라가요.');
      days.push(
        {date:'입국일',title:'저녁 CDG에서 바로 스트라스부르',subtitle:'16:50 도착 → 18:53 직통 TGV 목표',steps:[step('france-arrival','arrival','파리 샤를드골공항 도착','cdg','16:50 도착 가정','입국심사와 수하물 수령을 마치면 곧바로 CDG 2 TGV역으로 이동해요.',{facts:['현재 참고 시간표: CDG 18:53 → 스트라스부르 21:04','실제 12월 시간표가 열리면 같은 구조로 시각 재확정']}),step('arrival-choice','choice','직통을 놓쳤다면','cdg','수하물 수령 직후 판단','18:53 직통을 탈 수 있으면 공항역으로, 놓쳤다면 RER B로 북역에 간 뒤 동역 20:25편을 노려요.',{choice:'cdgFallback',choiceLabel:'직통 놓침 · 파리 동역 경유',skipLabel:'CDG 직통 TGV 이용'}),journey('cdg-direct','CDG 2 TGV → 스트라스부르','strasHotel','18:53~21:30 목표',['terminal-cdgrail','cdg-stras','stras-hotel'],'공항에서 직통 TGV를 타고 스트라스부르역 도착 후 바로 숙소에 체크인해요.',{without:'cdgFallback',highlights:['별도 발권 연결이므로 교환·환불 조건 좋은 운임 권장','열차 출발 2분 전에는 승강장 탑승 준비']}),journey('fallback-est','CDG → 파리 동역','parisEst','직통을 놓친 즉시',['terminal-cdgrail','cdg-nord','nord-est'],'RER B로 파리 북역까지 간 뒤 인접한 동역으로 걸어요.',{branch:'cdgFallback'}),journey('fallback-stras','파리 동역 → 스트라스부르','strasHotel','20:25 전후 출발 목표',['paris-stras','stras-hotel'],'현재 참고 시간표의 마지막 TGV로 이동해 늦게 체크인해요. 실제 여행일 운행 여부와 좌석을 반드시 재확인합니다.',{branch:'cdgFallback'})]},
        {date:'2일차',title:'스트라스부르 첫날',subtitle:'늦잠 뒤 쁘띠 프랑스부터 천천히',steps:[journey('stras-first','쁘띠 프랑스 첫 산책','petite','10:30 이후',['hotel-petite'],'전날 늦게 도착하므로 아침을 서두르지 않고 운하와 목조가옥 지구부터 걸어요.',{photo:'petite'}),journey('stras-first-cat','스트라스부르 대성당','cathedral','오후',['petite-cat'],'쁘띠 프랑스에서 구시가지를 지나 대성당까지 이어 걸어요.',{photo:'stras'})]},
        {date:'3일차',title:'스트라스부르 크리스마스 중심부',subtitle:'대성당·광장·야간 조명',steps:[journey('stras-cathedral','대성당과 구시가지','cathedral','09:30',['hotel-petite','petite-cat'],'쁘띠 프랑스를 거쳐 대성당으로 걸어요.',{photo:'stras'}),journey('stras-kleber','클레베르 광장','kleber','오후~밤',['cat-kleber'],'광장 대형 트리와 주변 마켓을 해 진 뒤 다시 봐요.',{highlights:['마켓 기간·보안구역은 해당 연도 재확인','주말 저녁 혼잡을 피해 평일 배치 가능']})]},
        {date:'4일차',title:'스트라스부르의 다른 얼굴',subtitle:'오랑주리 공원과 유럽지구',steps:[journey('stras-orangerie-day','오랑주리 공원','orangerie','오전',['hotel-stras','stras-orangerie'],'트램과 도보로 공원까지 이동해요.'),journey('stras-europe','유럽의회 지구','european','오후',['orangerie-eu'],'공원에서 유럽기관 건축물을 이어 봐요.',{photo:'stras'}),journey('stras-lastnight','구시가지 마지막 밤','cathedral','저녁',['eu-cat'],'트램으로 중심부에 돌아와 놓친 마켓을 정리해요.',{highlights:['다음 날 TGV 출발역·승강장 확인']})]},
        {date:'5일차',title:'스트라스부르에서 파리로',subtitle:'오전 TGV · 오후 루브르 축',steps:[journey('to-paris','스트라스부르 → 파리 동역','parisEst','09:00~11:00',['hotel-stras','stras-paris'],'직통 TGV 지정석으로 파리 동역까지 이동해요.'),journey('paris-checkin','파리 숙소에 짐 맡기기','parisHotel','도착 후',['est-photel'],'동역권 숙소에 짐을 맡겨 환승을 단순하게 해요.'),journey('paris-louvre','루브르와 튈르리','tuileries','오후',['photel-est','est-louvre','louvre-tuileries'],'숙소에서 동역으로 돌아가 지하철을 타요. 루브르 내부는 예약한 경우에만 넣어요.',{photo:'louvre'}),journey('paris-concorde','콩코르드 광장','concorde','해 질 무렵',['tuileries-concorde'],'튈르리 서쪽으로 걸어 첫 파리 야경을 맞아요.') ]},
        {date:'6일차',title:'시테섬과 생제르맹',subtitle:'센강 남쪽을 느긋하게',steps:[journey('paris-notre','노트르담 대성당','notre','09:30',['photel-est','est-notre'],'Métro 4로 시테섬까지 이동해요.',{photo:'paris'}),journey('paris-sg','생제르맹데프레','saintGermain','오후',['notre-sg'],'서점과 카페를 골라 센강 남안을 걸어요.',{highlights:['생트샤펠을 넣으면 시간예약','한겨울에는 실내 카페 휴식 확보']})]},
        {date:'7일차',title:'몽마르트와 개선문',subtitle:'북쪽 언덕에서 서쪽 대로로',steps:[journey('paris-montmartre','몽마르트','montmartre','09:30',['photel-est','est-montmartre'],'앙베르역권에서 푸니쿨라 또는 계단으로 사크레쾨르에 올라요.',{photo:'montmartre'}),journey('paris-arc','개선문','arc','오후',['montmartre-arc'],'Métro 2로 도시 북쪽을 가로질러 개선문으로.',{highlights:['개선문 전망대는 일몰 시간대 예약 후보','소매치기 주의']})]},
        {date:'8일차',title:'에펠탑과 센강',subtitle:'파리의 대표 야경을 한 번에',steps:[journey('paris-eiffel','트로카데로 → 에펠탑','eiffel','오후~밤',['photel-est','est-arc','arc-eiffel'],'숙소에서 개선문을 거쳐 트로카데로로 이동하고 센강을 건너요.',{photo:'paris',highlights:['에펠탑 입장권은 공식 사이트 우선','겨울 점등·반짝임 시간 재확인']})]},
        {date:'9일차',title:'파리 자유일',subtitle:'예약이 가장 어려운 한 곳을 넣는 완충일',steps:[step('paris-free','visit','미술관 또는 동네 하나','louvre','하루','루브르·오르세·오랑주리 중 예약한 한 곳, 또는 마레 산책처럼 취향에 맞는 한 축만 선택해요.',{photo:'louvre',highlights:['휴관일을 보고 Day 6~9 순서 교체','쇼핑·세탁·짐 정리 시간 확보']})]},
        {date:'출국일',title:'낮 비행기로 CDG 출국',subtitle:'14시 출발 가정 · 공항 3시간 전 도착',steps:[step('paris-checkout','departure','체크아웃','parisHotel','08:30','아침 식사 뒤 체크아웃하고 북역 RER B로 걸어가요.'),journey('cdg-transfer','파리 북역 → CDG','cdgRail','09:30',['photel-nord','nord-cdg'],'공항행 종착지를 확인하고 RER B에 탑승해요.'),journey('cdg-depart','파리 출국','cdg','11:00 공항 도착 · 14:00 출발 가정',['cdgrail-terminal'],'예약 항공사의 터미널로 이동해 체크인·출국심사를 마쳐요.') ]}
      );
    }});
  })();

  return {12:east,13:north,14:france};
})();
if (typeof window !== 'undefined') window.CITY_TRIPS=CITY_TRIPS;
if (typeof module !== 'undefined') module.exports=CITY_TRIPS;
