/* Course 12–14: shared card-and-map presentation used by the Tokyo itinerary. */
window.CITY_TRIPS={
  12:{meta:{name:'뮌헨 → 드레스덴 → 베를린 → 바르샤바',period:'날짜 미정 · 동유럽 겨울 도시 여행'},center:[13.40,50.70],zoom:5.2,places:{munich:{name:'뮌헨',coords:[11.582,48.135]},neusch:{name:'노이슈반슈타인 성',coords:[10.7498,47.5576]},dresden:{name:'드레스덴 알트마르크트',coords:[13.737,51.045]},berlin:{name:'브란덴부르크 문',coords:[13.3777,52.5163]},warsaw:{name:'바르샤바 구시가지',coords:[21.0122,52.2297]}},lines:{},legs:{},photos:{},days:[
    {date:'Day 1',title:'뮌헨에 도착해 겨울의 시작',subtitle:'도착일은 구시가지와 따뜻한 저녁에 집중.',steps:[{id:'munich-arrive',kind:'visit',title:'뮌헨 입국 · 구시가지 산책',place:'munich',time:'도착 후',detail:'마리엔 광장과 빅투알리엔마르크트 주변을 가볍게 걸으며 첫날의 리듬을 맞춰요.',highlights:['마리엔 광장', '빅투알리엔마르크트', '바이에른식 저녁']}]},
    {date:'Day 2',title:'바이에른의 하루',subtitle:'노이슈반슈타인 또는 뮌헨 시내를 고르는 날.',steps:[{id:'neusch',kind:'visit',title:'노이슈반슈타인 당일치기',place:'neusch',time:'아침~저녁',detail:'성 내부 시간 지정 투어와 마리엔교 풍경을 중심으로 두고, 어두워지기 전 뮌헨으로 돌아와요.',highlights:['시간 지정 관람권 사전 예약', '겨울철 일몰·다리 출입 확인']}]},
    {date:'Day 3',title:'드레스덴으로',subtitle:'긴 이동 뒤에는 크리스마스 마켓과 구시가지 야경.',steps:[{id:'dresden',kind:'visit',title:'드레스덴 · 슈트리첼마르크트',place:'dresden',time:'오후~밤',detail:'뮌헨에서 이동한 뒤 알트마르크트, 프라우엔키르헤와 엘베강 야경을 천천히 즐겨요.',highlights:['슈톨렌과 글뤼바인', '프라우엔키르헤 야경']}]},
    {date:'Day 4',title:'드레스덴의 겨울',subtitle:'마켓과 바로크 구시가지를 온전히.',steps:[{id:'dresden-full',kind:'visit',title:'드레스덴 구시가지',place:'dresden',time:'하루',detail:'츠빙거, 젬퍼오퍼, 브륄 테라스를 걸으며 드레스덴의 낮과 밤을 모두 남겨요.',highlights:['츠빙거 궁전', '젬퍼오퍼', '엘베강 산책']}]},
    {date:'Day 5',title:'베를린으로',subtitle:'박물관과 역사, 서로 다른 도시의 공기.',steps:[{id:'berlin',kind:'visit',title:'베를린 첫 산책',place:'berlin',time:'오후~밤',detail:'드레스덴에서 이동한 뒤 브란덴부르크 문과 운터 덴 린덴을 걸으며 베를린의 밤을 시작해요.',highlights:['브란덴부르크 문', '운터 덴 린덴']}]},
    {date:'Day 6',title:'베를린의 하루',subtitle:'보고 싶은 테마에 맞춰 깊게.',steps:[{id:'berlin-full',kind:'visit',title:'베를린을 고르는 날',place:'berlin',time:'하루',detail:'박물관섬, 이스트사이드 갤러리, 크로이츠베르크 중 취향에 맞는 두세 곳만 골라 여유를 남겨요.',highlights:['박물관섬 또는 이스트사이드 갤러리', '예약한 저녁 식사']}]},
    {date:'Day 7',title:'바르샤바로',subtitle:'여행의 마지막 도시는 가볍고 느긋하게.',steps:[{id:'warsaw',kind:'visit',title:'바르샤바 구시가지',place:'warsaw',time:'오후~밤',detail:'베를린에서 이동해 왕궁광장과 구시가지를 걷고, 폴란드식 저녁으로 마지막 도시를 만나요.',highlights:['왕궁광장', '구시가지 야경']}]},
    {date:'Day 8',title:'바르샤바의 마지막 하루',subtitle:'카페와 산책, 귀국 준비.',steps:[{id:'warsaw-full',kind:'visit',title:'바르샤바를 천천히',place:'warsaw',time:'하루',detail:'구시가지와 신시가지 사이를 걷고 카페에서 여행을 정리해요. 귀국편 시간에 맞춰 공항 이동을 확정합니다.',highlights:['문화과학궁전 주변', '귀국편·수하물 확인']}]}]},
  13:{meta:{name:'프랑크푸르트 → 함부르크',period:'날짜 미정 · 독일 서부와 북부'},center:[9.95,51.20],zoom:5.5,places:{frankfurt:{name:'프랑크푸르트 뢰머베르크',coords:[8.6821,50.1109]},heidelberg:{name:'하이델베르크 성',coords:[8.7158,49.4104]},cologne:{name:'쾰른 대성당',coords:[6.9583,50.9413]},hamburg:{name:'함부르크 엘프필하모니',coords:[9.984,53.5413]}},lines:{},legs:{},photos:{},days:[
    {date:'Day 1',title:'프랑크푸르트에 도착',subtitle:'뢰머베르크와 마인강으로 시작.',steps:[{id:'fra',kind:'visit',title:'프랑크푸르트 첫 산책',place:'frankfurt',time:'도착 후',detail:'숙소에 짐을 두고 뢰머베르크, 아이제르너 다리와 작센하우젠을 가볍게 연결해요.',highlights:['뢰머베르크', '마인강 야경']}]},
    {date:'Day 2',title:'프랑크푸르트',subtitle:'금융도시와 구시가지의 대비.',steps:[{id:'fra-full',kind:'visit',title:'프랑크푸르트의 하루',place:'frankfurt',time:'하루',detail:'구시가지와 박물관강변 중 취향에 맞는 곳을 고르고, 저녁은 작센하우젠에서 보내요.',highlights:['신 구시가지', '박물관강변']}]},
    {date:'Day 3',title:'하이델베르크 당일치기',subtitle:'성, 철학자의 길, 네카어강.',steps:[{id:'heidelberg',kind:'visit',title:'하이델베르크 성과 구시가지',place:'heidelberg',time:'아침~저녁',detail:'프랑크푸르트에서 당일치기로 다녀와 성과 알테 브뤼케, 구시가지를 느긋하게 걸은 뒤 돌아와요.',highlights:['하이델베르크 성', '알테 브뤼케', '저녁 프랑크푸르트 귀환']}]},
    {date:'Day 4',title:'쾰른 당일치기',subtitle:'대성당과 라인강.',steps:[{id:'cologne',kind:'visit',title:'쾰른 대성당',place:'cologne',time:'아침~저녁',detail:'대성당을 중심으로 구시가지와 라인강변을 보고, 해 지기 전 또는 저녁에 프랑크푸르트로 돌아와요.',highlights:['쾰른 대성당', '호엔촐레른 다리', '저녁 프랑크푸르트 귀환']}]},
    {date:'Day 5',title:'함부르크로',subtitle:'항구도시의 밤으로 마무리.',steps:[{id:'hamburg',kind:'visit',title:'함부르크 항구 야경',place:'hamburg',time:'오후~밤',detail:'프랑크푸르트에서 북상해 엘프필하모니와 하펜시티, 슈파이허슈타트를 걷습니다.',highlights:['엘프필하모니', '슈파이허슈타트']}]},
    {date:'Day 6',title:'함부르크의 하루',subtitle:'물가와 동네의 여유.',steps:[{id:'hamburg-full',kind:'visit',title:'함부르크를 천천히',place:'hamburg',time:'하루',detail:'알스터 호수와 장크트파울리·피시마르크트 중 원하는 결을 골라 항구도시의 하루를 완성해요.',highlights:['알스터 호수', '항구 산책', '출국 또는 다음 여정 준비']}]}]},
  14:{meta:{name:'스트라스부르 → 파리',period:'크리스마스 시즌 · 날짜 확정 전'},center:[4.8,48.55],zoom:6.2,places:{strasbourg:{name:'스트라스부르 대성당',coords:[7.7521,48.5818]},petite:{name:'쁘띠 프랑스',coords:[7.743,48.581]},paris:{name:'에펠탑',coords:[2.2945,48.8584]},montmartre:{name:'사크레쾨르 대성당',coords:[2.3499,48.8867]}},lines:{},legs:{},photos:{},days:[
    {date:'Day 1',title:'스트라스부르에 도착',subtitle:'크리스마스의 수도에서 시작.',steps:[{id:'strasbourg-arrive',kind:'visit',title:'대성당과 쁘띠 프랑스',place:'strasbourg',time:'도착 후',detail:'호텔에 짐을 두고 대성당 광장과 쁘띠 프랑스를 걸으며 첫 마켓의 불빛을 만나요.',highlights:['스트라스부르 대성당', '글뤼바인과 알자스 간식']}]},
    {date:'Day 2',title:'스트라스부르 크리스마스',subtitle:'마켓을 서두르지 않고 즐기는 날.',steps:[{id:'strasbourg-full',kind:'visit',title:'크리스마스 마켓과 알자스',place:'petite',time:'하루',detail:'낮에는 운하와 골목을 걷고, 해가 진 뒤 광장마다 다른 마켓을 골라 천천히 돌아봐요.',highlights:['클레베르 광장 트리', '크리스킨델스메리크', '알자스 와인 바']}]},
    {date:'Day 3',title:'파리로',subtitle:'TGV를 타고 연말의 파리로.',steps:[{id:'paris-arrive',kind:'visit',title:'파리의 첫 밤',place:'paris',time:'오후~밤',detail:'스트라스부르에서 TGV로 이동해 숙소에 짐을 두고 센강과 에펠탑 야경을 봐요.',highlights:['센강 산책', '에펠탑 야경']}]},
    {date:'Day 4',title:'파리의 크리스마스',subtitle:'불빛과 예약한 식사의 날.',steps:[{id:'paris-xmas',kind:'visit',title:'샹젤리제 크리스마스 조명',place:'paris',time:'오후~밤',detail:'낮에는 느긋하게 쉬고, 해 진 뒤 샹젤리제와 개선문을 걸어요. 저녁 식당은 미리 예약합니다.',highlights:['샹젤리제 조명', '크리스마스 디너 예약']}]},
    {date:'Day 5',title:'파리의 하루',subtitle:'미술관과 동네를 한 가지 결로.',steps:[{id:'paris-full',kind:'visit',title:'파리를 고르는 날',place:'paris',time:'하루',detail:'루브르·오르세 같은 미술관 또는 마레·생제르맹 산책 중 하나에 집중하고, 너무 많은 예약은 피합니다.',highlights:['미술관 예약 확인', '마레 또는 생제르맹']}]},
    {date:'Day 6',title:'몽마르트와 귀국 준비',subtitle:'마지막 밤을 작게, 오래.',steps:[{id:'montmartre',kind:'visit',title:'몽마르트의 마지막 밤',place:'montmartre',time:'오후~밤',detail:'사크레쾨르 주변을 걷고 카페에서 여행을 정리해요. 다음 날 출국 시간을 기준으로 공항 이동을 준비합니다.',highlights:['사크레쾨르 야경', '공항 이동 확인']}]}]}
};
